#%RAML 1.0 Trait

responses:
  400:
    body:
      application/json:
        example:
          value:  'Unauthorized Access'
  401:
    body:
      application/json:
        example:
          value: 'Bad Request'
  404:
    body:
      application/json:
        example:
          value: 'Resource not found'
  500:
    body:
      application/json:
        example:
          value: 'Internal Server Error
