#%RAML 1.0 NamedExample
orderexample:
value:
  -
    OrderID: OID1
    ProductID: PID1
    ProductName: Prod1
    CustomerID: CID1
    OrderDate: 2020-12-24T05:30:00
    Quantity: 1
    ShipDate: 2020-12-24T05:36:23
    TotalPrice: 12345.00
    PaymentDate: 2020-12-24T05:37:54
    PaymentStatus: Success
    ShippingAddress: 123 High Street, New York, USA

  -
    OrderID: OID2
    ProductID: PID2
    ProductName: Prod2
    CustomerID: CID2
    OrderDate: 2020-12-24T05:30:00
    Quantity: 5
    ShipDate: 2020-12-24T05:36:23
    TotalPrice: 712345.00
    PaymentDate: 2020-12-24T05:37:54
    PaymentStatus: Success
    ShippingAddress: 123 Low Street, Arizona, USA

