#%RAML 1.0 DataType
type: object
properties:
  ProductId:
    example: PID1
    type: string
  ProductName:
    example: Prod1
    type: string 
  ProductDesc:
    example: Dummy product
    type: string
  UnitPrice:
    example: 345.23
    type: number
  AvailableUnits:
    example: 20
    type: integer
  