#%RAML 1.0 NamedExample
productexample:
value:
  -
    ProductId: PID1
    ProductName: Prod1
    ProductDesc: Dummy product
    UnitPrice: 345.23
    AvailableUnits: 20

  -
    ProductId: PID2
    ProductName: Prod2
    ProductDesc: Dummy product 2
    UnitPrice: 3345.23
    AvailableUnits: 200

  -
    ProductId: PID3
    ProductName: Prod3
    ProductDesc: Dummy product 3
    UnitPrice: 76345.23
    AvailableUnits: 2